# Generated by Django 3.0.7 on 2020-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
