# Generated by Django 3.0.7 on 2020-06-20 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200620_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='city',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='email',
            field=models.CharField(default='abc@xyz.in', max_length=256, validators=[django.core.validators.EmailValidator('The Entered Email is not valid.')]),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='name',
            field=models.CharField(default='abc', max_length=256),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='state',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
