# Generated by Django 3.0.7 on 2020-06-20 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200620_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='email',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator('The Entered Email is not valid.')]),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='state',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
