# Generated by Django 3.0.7 on 2020-06-20 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200620_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='email',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.EmailValidator('The Entered Email is not valid.')]),
        ),
    ]
