# Generated by Django 3.0.7 on 2020-06-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
