# Generated by Django 3.0.7 on 2020-06-20 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200620_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='city',
            field=models.CharField(default='none', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='email',
            field=models.CharField(default='abc@xyz.com', max_length=256, validators=[django.core.validators.EmailValidator('The Entered Email is not valid.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsofdoctors',
            name='state',
            field=models.CharField(default='none', max_length=256),
            preserve_default=False,
        ),
    ]
