# Generated by Django 3.0.7 on 2020-06-20 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200620_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsofdoctors',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
