# Generated by Django 3.0.7 on 2020-06-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_detailsofdoctors_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=2)),
                ('Disease', models.TextField()),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
