# Generated by Django 3.0.7 on 2020-06-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='Hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.DetailsOfDoctors'),
            preserve_default=False,
        ),
    ]
